### ISSUE TITLE
Current release version doesn't work

### ISSUE THREAD

**Issue by TremendoDude** [TooPick/gdoc-journals-foundry-vtt#1]
The current release of the module, along with missing the "lang" folder entirely, doesn't create the button at the top of journal entries. However, the current Main version of the module seems to work perfectly. Please update the release version!

Also, thanks so much for making this! It's gonna be a huge help with collaborative note taking for the sessions I play in moving forward!

**Comment by TooPick** [comment]
I'll try to fix that tomorrow, i'll also add the new "update all" functionality at the same time ! ;)

**Comment by TooPick** [comment]
Hey, I've just fixed the workflow issue that didn't zip the module correctly (it's the first module that i'm publishing, so i'm still learning how to do things...).
I've made a new release that works now and added an "update all" button on the journal page that searches all journals and updates them without opening each one.
Hope this module will help you !
If you have any ideas to improve the module, just tell me !
Have a nice day ! ;)
