### ISSUE TITLE
Doesn't seem to be working currently

### ISSUE THREAD

**Issue by bitbyter9** [TooPick/gdoc-journals-foundry-vtt#9]
All I get in the journal after inputting the document link and clicking update is a text copy of the link in the Journal. Seems like it may be currently broken by a recent update?

FoundryVTT Version: 12.331

**Comment by TooPick** [comment]
Hi, 
Sorry for the issue...
My service that is translating GoogleDocs to html was down, it should be up now, let me know if it's ok now.

**Comment by bitbyter9** [comment]
Yep, seems to be working now. Thank you!
